=== spresnac/webedition-unittests/webEdition/lib/we/app/defaults/applications.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--- Describes an webEdition application -->
<!ELEMENT manifest (creator,maintainer?,thirdparty*,info,requirements)>

<!ENTITY % _person "((authors|author)?,location,year+)" >
<!ENTITY % _versionReq "minVersion CDATA #REQUIRED maxVersion CDATA #IMPLIED" >
<!ENTITY % _versionOpt "minVersion CDATA #IMPLIED maxVersion CDATA #IMPLIED" >
<!ENTITY % _lang "lang (de|en|fr) #REQUIRED" >

<!--- Detailed information about the initial author -->
<!ELEMENT creator (company|person)* >

<!--- Detailed information about the maintainers -->
<!ELEMENT maintainer (company|person)* >

<!--- provide information about the company -->
<!ELEMENT company ((authors|author)?,location+,year+) >
<!ATTLIST company
	name	CDATA #REQUIRED
>
<!--- provide information about an individual person -->
<!ELEMENT person ((authors|author)?,location,year+)>

<!--- provide information about 3rd-party product with name and version -->
<!ELEMENT thirdparty ((company|person),license) >
<!ATTLIST thirdparty
	name CDATA #REQUIRED
	version CDATA #REQUIRED
>

<!--- author's details -->
<!ELEMENT author EMPTY>
<!ATTLIST author
	name CDATA #REQUIRED
	url CDATA #IMPLIED
	email CDATA #IMPLIED
>

<!--- if more than one author -->
<!ELEMENT authors (author*) >

<!--- provide detailed adress information -->
<!ELEMENT location (address?,phone?,fax?,email+,www*) >
<!ATTLIST location
	country (DE|GB|PL|IT|FR) #REQUIRED
>


<!--- postal contact address -->
<!ELEMENT address (#PCDATA)>

<!--- phone number (international format +xx yy) -->
<!ELEMENT phone (#PCDATA)>

<!--- fax number (international format +xx yy) -->
<!ELEMENT fax (#PCDATA)>

<!--- email-adress for contact format name@domain.tld -->
<!ELEMENT email (#PCDATA)>

<!--- homepage with link text -->
<!ELEMENT www (#PCDATA)*>
<!ATTLIST www
	url CDATA #REQUIRED
>

<!--- provide a year -->
<!ELEMENT year (#PCDATA)>

<!--- provide information about the application itself <br/>appName is the Name of the application -->
<!ELEMENT info (class+,license,title+,description+,features?,(categories|category))>
<!ATTLIST info
	appName CDATA #REQUIRED
	encoding (ISO8859-1|ISO8859-15|UTF8) "UTF8"
>
<!--- name all classes introduced by this application -->
<!ELEMENT class (#PCDATA)>

<!--- name the license, version and where to find the licence -->
<!ELEMENT license EMPTY >
<!ATTLIST license
	name CDATA #REQUIRED
	version CDATA #REQUIRED
	url CDATA #REQUIRED
>

<!--- give the application a title shown on selection <br/> lang must specify the language of the title -->
<!ELEMENT title (#PCDATA)>
<!ATTLIST title %_lang; >

<!--- explain, what this application is about<br/> lang must specify the language of the title -->
<!ELEMENT description (#PCDATA)>
<!ATTLIST description %_lang; >

<!--- feature set tells how webEdition handles this application <br/> default values are shown -->
<!ELEMENT features EMPTY >
<!ATTLIST features
	supportshooks (true|false) "false"
	deactivatable (true|false) "true"
	deinstallable (true|false) "true"
	updatable (true|false) "true"
>

<!--- in which categories (if more than one) should this application appear -->
<!ELEMENT categories (category)*>

<!--- name the category -->
<!ELEMENT category (#PCDATA)>

<!--- which requirements must be fulfilled in order to run this application -->
<!ELEMENT requirements (php,webedition)>

<!--- details about php itself<br/>you must provide a minimum version number -->
<!ELEMENT php (extension*)>
<!ATTLIST php %_versionReq; >

<!--- if specific php extensions need to be installed, name these, and if applicable its versionnumbers -->
<!ELEMENT extension (#PCDATA) >
<!ATTLIST extension %_versionOpt; >

<!--- name all dependencies concerning webedition itself, a versionnumber is needed -->
<!ELEMENT webedition (sdk,module*,application*) >
<!ATTLIST webedition %_versionReq; >

<!--- name the sdk versionnumbers needed -->
<!ELEMENT sdk EMPTY >
<!ATTLIST sdk %_versionReq; >

<!--- name all modules, that need to be enabled -->
<!ELEMENT module (#PCDATA)>
<!ATTLIST module %_versionOpt; >

<!--- name all additional applications that need to be installed before this application can be run -->
<!ELEMENT application (#PCDATA)>
<!ATTLIST application %_versionOpt; >

=== spresnac/webedition-unittests/webEdition/lib/we/app/defaults/manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE manifest SYSTEM "applications.dtd">
<!-- default manifest for webEdition applications -->
<manifest>
	<creator>
		<company name="webEdition e.V.">
			<author name="webedition.org" />
			<location country="DE">
				<address>Innsbrucker Str. 35, 10825 Berlin</address>
				<phone>+49 30 766835-79</phone>
				<fax>+49 30 766835-85</fax>
				<email>info@webedition.org</email>
				<www url="http://www.webedition.org">Webedtion Homepage</www>
			</location>
			<year>2010</year>
		</company>
	</creator>

	<info appName="exampleApplication">
		<class>exampleApplication</class>
		<license name="GPL" version="3" url="http://www.gnu.org/licenses/gpl.html"/>
		<title lang="de">Meine we-Applikation</title>
		<description lang="de">Keine Beschreibung vorhanden!</description>
		<category>miscellaneous</category>
	</info>

	<requirements>
		<php minVersion="5.2.4">
			<extension>simplexml</extension>
			<extension>gdlib</extension>
		</php>
		<webedition minVersion="6.1.0">
			<sdk minVersion="6.1.0"/>
		</webedition>
	</requirements>

</manifest>

=== spresnac/webedition-unittests/webEdition/lib/we/app/defaults/sample-manifest.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE manifest SYSTEM "applications.dtd">
<!-- example manifest for webEdition applications showing examples of all supported values -->
<manifest>
	<creator>
		<company name="webEdition e.V.">
			<authors>
				<author name="myname" email="contact@direct.de"/>
				<author name="another author's name" url="http://www.myHomepage.de"/>
			</authors>
			<location country="DE">
				<address>c/o LÃ¶wi &amp; Partner, Innsbrucker Str. 35, 10825 Berlin</address>
				<phone>+49 30 766835-79</phone>
				<fax>+49 30 766835-85</fax>
				<email>info@webedition.org</email>
				<www url="http://www.webedition.org">webEdition-Site</www>
			</location>
			<location country="FR">
				<address>somewhere in france</address>
				<phone>+33 1234556</phone>
				<fax>+33 1234557</fax>
				<email>email@url.fr</email>
				<www url="http://www.xyz.fr">we speak french</www>
			</location>
			<year>2010</year>
		</company>
		<person>
			<author name="me"/>
			<location country="DE">
				<email>me@my.de</email>
			</location>
			<year>2011</year>
		</person>

	</creator>

	<maintainer>
		<person>
			<author name="my-author"/>
			<location country="DE">
		<!-- no adress provided -->
				<email>info@webedition.org</email>
			</location>
			<year>2010</year>
		</person>
	</maintainer>

	<thirdparty name="external Aplication" version="1.0">
		<company name="someComp">
			<author name="who ever" />
			<location country="DE">
				<email>test@test.de</email>
			</location>
			<year>2011</year>
		</company>
		<license name="GPL" version="2" url="http://www.gnu.org/licenses/gpl.html"/>
	</thirdparty>

	<info appName="testApp" encoding="ISO8859-15">
		<class>myClass</class>
		<license name="GPL" version="3" url="http://www.gnu.org/licenses/gpl.html" />
		<title lang="de">meine erste Applikation</title>
		<title lang="en">my first application</title>
		<description lang="de">sie macht irgendwas keine Ahnung was</description>
		<description lang="en">I don't exactly know what it is supposed to do</description>
		<features supportshooks="true" deactivatable="false" deinstallable="false" updatable="false"/>
		<categories>
			<category>simpleTool</category>
			<category>complexTool</category>
		</categories>
	</info>

	<requirements>
		<php minVersion="5.2.0">
			<extension minVersion="1.0">simplexml</extension>
			<extension maxVersion="2.0">gdlib</extension>
		</php>
		<webedition minVersion="6.1.0">
			<sdk minVersion="6.1.0" maxVersion="6.3.0"></sdk>
			<module>customer</module>
			<module>shop</module>
			<application minVersion="0.9">anotherApplication</application>
		</webedition>
	</requirements>

</manifest>
